export const suras = [
    { name: "Al-Fatihah", id: 1 },
    { name: "Al-Baqarah", id: 2 },
    { name: "Al-Imran", id: 3 },
    { name: "An-Nisa", id: 4 },
    { name: "Al-Maidah", id: 5 },
    { name: "Al-Anam", id: 6 },
    { name: "Al-Araf", id: 7 },
    { name: "Al-Anfal", id: 8 },
    { name: "Al-Tawbah", id: 9 },
    { name: "Yunus", id: 10 },
    { name: "Hud", id: 11 },
    { name: "Yusuf", id: 12 },
    { name: "Ar-Rad", id: 13 },
    { name: "Ibrahim", id: 14 },
    { name: "Al-Hijr", id: 15 },
    { name: "An-Nahl", id: 16 },
    { name: "Al-Isra", id: 17 },
    { name: "Al-Kahf", id: 18 },
    { name: "Maryam", id: 19 },
    { name: "Taha", id: 20 },
    { name: "Al-Anbiya", id: 21 },
    { name: "Al-Hajj", id: 22 },
    { name: "Al-Muminun", id: 23 },
    { name: "An-Nur", id: 24 },
    { name: "Al-Furqan", id: 25 },
    { name: "Ash-Shuara", id: 26 },
    { name: "An-Naml", id: 27 },
    { name: "Al-Qasas", id: 28 },
    { name: "Al-Ankabut", id: 29 },
    { name: "Ar-Rum", id: 30 },
    { name: "Luqman", id: 31 },
    { name: "As-Sajdah", id: 32 },
    { name: "Al-Ahzab", id: 33 },
    { name: "Saba", id: 34 },
    { name: "Fatir", id: 35 },
    { name: "Ya-Sin", id: 36 },
    { name: "As-Saffat", id: 37 },
    { name: "Sad", id: 38 },
    { name: "Az-Zumar", id: 39 },
    { name: "Ghafir", id: 40 },
    { name: "Fussilat", id: 41 },
    { name: "Ash-Shura", id: 42 },
    { name: "Az-Zukhruf", id: 43 },
    { name: "Ad-Dukhan", id: 44 },
    { name: "Al-Jathiya", id: 45 },
    { name: "Al-Ahqaf", id: 46 },
    { name: "Muhammad", id: 47 },
    { name: "Al-Fath", id: 48 },
    { name: "Al-Hujurat", id: 49 },
    { name: "Qaf", id: 50 },
    { name: "Az-Zariyat", id: 51 },
    { name: "At-Tur", id: 52 },
    { name: "An-Najm", id: 53 },
    { name: "Al-Qamar", id: 54 },
    { name: "Ar-Rahman", id: 55 },
    { name: "Al-Waqiah", id: 56 },
    { name: "Al-Hadid", id: 57 },
    { name: "Al-Mujadilah", id: 58 },
    { name: "Al-Hashr", id: 59 },
    { name: "Al-Mumtahanah", id: 60 },
    { name: "As-Saff", id: 61 },
    { name: "Al-Jumuah", id: 62 },
    { name: "Al-Munafiqun", id: 63 },
    { name: "At-Taghabun", id: 64 },
    { name: "At-Talaq", id: 65 },
    { name: "At-Tahrim", id: 66 },
    { name: "Al-Mulk", id: 67 },
    { name: "Al-Qalam", id: 68 },
    { name: "Al-Haqqah", id: 69 },
    { name: "Al-Maarij", id: 70 },
    { name: "Nuh", id: 71 },
    { name: "Al-Jinn", id: 72 },
    { name: "Al-Muzzammil", id: 73 },
    { name: "Al-Muddaththir", id: 74 },
    { name: "Al-Qiyamah", id: 75 },
    { name: "Al-Insan", id: 76 },
    { name: "Al-Mursalat", id: 77 },
    { name: "An-Naba", id: 78 },
    { name: "An-Nazi`at", id: 79 },
    { name: "`Abasa", id: 80 },
    { name: "At-Takwir", id: 81 },
    { name: "Al-Infitar", id: 82 },
    { name: "Al-Mutaffifin", id: 83 },
    { name: "Al-Inshiqaq", id: 84 },
    { name: "Al-Buruj", id: 85 },
    { name: "At-Tariq", id: 86 },
    { name: "Al-A`la", id: 87 },
    { name: "Al-Ghashiyah", id: 88 },
    { name: "Al-Fajr", id: 89 },
    { name: "Al-Balad", id: 90 },
    { name: "Ash-Shams", id: 91 },
    { name: "Al-Lail", id: 92 },
    { name: "Ad-Duha", id: 93 },
    { name: "Ash-Sharh", id: 94 },
    { name: "At-Tin", id: 95 },
    { name: "Al-Alaq", id: 96 },
    { name: "Al-Qadr", id: 97 },
    { name: "Al-Bayyinah", id: 98 },
    { name: "Az-Zalzalah", id: 99 },
    { name: "Al-Adiyat", id: 100 },
    { name: "Al-Qari`ah", id: 101 },
    { name: "At-Takathur", id: 102 },
    { name: "Al-Asr", id: 103 },
    { name: "Al-Humazah", id: 104 },
    { name: "Al-Fil", id: 105 },
    { name: "Quraysh", id: 106 },
    { name: "Al-Ma`un", id: 107 },
    { name: "Al-Kawthar", id: 108 },
    { name: "Al-Kafirun", id: 109 },
    { name: "An-Nasr", id: 110 },
    { name: "Al-Masad", id: 111 },
    { name: "Al-Ikhlas", id: 112 },
    { name: "Al-Falaq", id: 113 },
    { name: "An-Nas", id: 114 },
]
export const surasAr = [
    'الفاتحة',
    'البقرة',
    'آل عمران',
    'النساء',
    'المائدة',
    'الأنعام',
    'الأعراف',
    'الأنفال',
    'التوبة',
    'يونس',
    'هود',
    'يوسف',
    'الرعد',
    'إبراهيم',
    'الحجر',
    'النحل',
    'الإسراء',
    'الكهف',
    'مريم',
    'طه',
    'الأنبياء',
    'الحج',
    'المؤمنون',
    'النور',
    'الفرقان',
    'الشعراء',
    'النمل',
    'القصص',
    'العنكبوت',
    'الرّوم',
    'لقمان',
    'السجدة',
    'الأحزاب',
    'سبأ',
    'فاطر',
    'يس',
    'الصافات',
    'ص',
    'الزمر',
    'غافر',
    'فصّلت',
    'الشورى',
    'الزخرف',
    'الدّخان',
    'الجاثية',
    'الأحقاف',
    'محمد',
    'الفتح',
    'الحجرات',
    'ق',
    'الذاريات',
    'الطور',
    'النجم',
    'القمر',
    'الرحمن',
    'الواقعة',
    'الحديد',
    'المجادلة',
    'الحشر',
    'الممتحنة',
    'الصف',
    'الجمعة',
    'المنافقون',
    'التغابن',
    'الطلاق',
    'التحريم',
    'الملك',
    'القلم',
    'الحاقة',
    'المعارج',
    'نوح',
    'الجن',
    'المزّمّل',
    'المدّثر',
    'القيامة',
    'الإنسان',
    'المرسلات',
    'النبأ',
    'النازعات',
    'عبس',
    'التكوير',
    'الإنفطار',
    'المطفّفين',
    'الإنشقاق',
    'البروج',
    'الطارق',
    'الأعلى',
    'الغاشية',
    'الفجر',
    'البلد',
    'الشمس',
    'الليل',
    'الضحى',
    'الشرح',
    'التين',
    'العلق',
    'القدر',
    'البينة',
    'الزلزله',
    'العاديات',
    'القارعة',
    'التكاثر',
    'العصر',
    'الهمزة',
    'الفيل',
    'قريش',
    'الماعون',
    'الكوثر',
    'الكافرون',
    'النصر',
    'المسد',
    'الإخلاص',
    'الفلق',
    'الناس'
]


